service: lambda-dart-sls

custom:
  defaultStage: dev

provider:
  name: aws
  runtime: provided
  timeout: 20
  region: ap-northeast-1
  ecr:
    images:
      appImage:
        path: ./
        platform: linux/amd64
  stage: ${opt:stage, self:custom.defaultStage}
  # environment:
  #   ${file(./env.yml)}

functions:
  hello:
    image:
      name: appImage
      command:
        - hello
    events:
      - http:
          path: hello
          method: get
