service: serverless-dart-sls

custom:
  defaultStage: dev
  api_version: v0

provider:
  name: aws
  runtime: provided
  region: ap-northeast-1
  stage: ${opt:stage, self:custom.defaultStage}

functions:
  hello:
    handler: hello
    events:
      - http:
          path: hello
          method: get
  world:
    handler: world
    events:
      - http:
          path: world
          method: post
